### PR TITLE
Fix documentation typo

### PR DESCRIPTION
**Pull request by Xeyame**
Took me a while to notice this in my own config :)

### CODE REVIEW

**Comment by Xeyame** [comment]
Acutally it turns out that entire page has wrong configuration options, might want to fix that.

**Comment by eikek** [comment]
Thanks for the typo fix!

> Acutally it turns out that entire page has wrong configuration options, might want to fix that.

The *entire page*? What exactly do you mean? I don't see any wrong options, can you give some examples? The last part is the default config as used by the app itself. I'm quite sure that this is correct.

**Comment by Xeyame** [comment]
I might have just been unlucky. The other one i came across was `sharry.restserver.baseurl`; it should be `sharry.restserver.base-url` and `sharry.restserver.signup` should be `sharry.restserver.backend.signup`, the `backend` part seems to be missing in more places.

However, the example config options work perfectly fine, pretty neat piece of software :), Thanks for making it!

**Comment by eikek** [comment]
Ouch, thank you! I was selecting some good ones :) and kept wondering. Yes, these are errors of course; I moved things around without updating the manual part of that page. I might just remove the surrounding pieces, as it should be obvious when looking at the default config where to put it.

**Pull request merged**
