### PR TITLE
#444 Clarify documentation & logging of cleanup job

### PR DESCRIPTION
**Pull request by Stamper-repo**

### CODE REVIEW

**Comment by Stamper-repo** [comment]
Will fix: https://github.com/eikek/sharry/issues/444

**Comment by eikek** [comment]
Hi @Stamper-repo thank you a lot! Nicely done! Sorry for this, I missed it to mention in the contribution guide :-S There is a format check in place. Could you run `sbt fix` to reformat all scala files to the format standard and push? thanks!

**Comment by Stamper-repo** [comment]
@eikek  Cheers! Not a problem, see the newly pushed commits! I also added the `sbt fix` formatting guide lines to the contribution page. Hopefully where you expect it!

**Comment by eikek** [comment]
> @eikek Cheers! Not a problem, see the newly pushed commits! I also added the `sbt fix` formatting guide lines to the contribution page. Hopefully where you expect it!

Thank you so much. Oops I think I just added it myself a minute ago :-) But no worries, I can clean this up later.

**Comment by Stamper-repo** [comment]
Hahahaha that is what I get for adding work without first confirming if it is wanted :P I am removing it now!

**Comment by Stamper-repo** [comment]
@eikek  Shall I add a link from the microsite dev.md to Contributing.md so new contributors know where to look for this stuff?

**Comment by eikek** [comment]
> Hahahaha that is what I get for adding work without first confirming if it is wanted :P I am removing it now!

Oh really sorry for this … bad timing here :-).


> @eikek Shall I add a link from the microsite dev.md to Contributing.md so new contributors know where to look for this stuff?

Ah yes, good idea!

**Pull request merged**
